generic-service:
  nameOverride: hmpps-workload

  replicaCount: 2

  image:
    repository: quay.io/hmpps/hmpps-workload
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: &ingressHost app-hostname.local # override per environment
    tlsSecretName: hmpps-workload-cert
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false
    annotations:
      nginx.ingress.kubernetes.io/custom-http-errors: "418"
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/** {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "stdout,logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    INGRESS_URL: *ingressHost
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-workload:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      APPLICATION_NOTIFY_KEY: "APPLICATION_NOTIFY_KEY"
    hmpps-workload-auth:
      OAUTH_CLIENT_ID: "SYSTEM_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-live-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSDOMAINTOPIC_ARN: "topic_arn"
    hmpps-workload-offender-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-workload-offender-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSOFFENDERQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-person-on-probation-events-dl-secret:
      HMPPS_SQS_QUEUES_TIERCALCQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-hmpps-audit-secret:
      HMPPS_SQS_QUEUES_HMPPSAUDITQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-staff-events-dl-secret:
      HMPPS_SQS_QUEUES_WORKLOADCALCULATIONQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-reductions-completed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSREDUCTIONSCOMPLETEDQUEUE_DLQ_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_QUEUE_NAME: "sqs_queue_name"
    hmpps-extract-placed-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_HMPPSEXTRACTPLACEDQUEUE_DLQ_NAME: "sqs_queue_name"
    sqs-prisoner-events-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-events-dl-secret:
      HMPPS_SQS_QUEUES_WORKLOADPRISONERQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    cymulate-1: 54.217.50.18/32
    cymulate-2: 52.208.202.111/32
    cymulate-3: 52.49.144.209/32
    groups:
      - internal

  serviceAccountName: "hmpps-workload"

generic-prometheus-alerts:
  targetApplication: hmpps-workload
  alertSeverity: hmpps-tier
