---
# Per environment values which override defaults in hmpps-workload/values.yaml

generic-service:

  ingress:
    host: hmpps-workload-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    DATABASE_NAME: hmpps_workload

generic-prometheus-alerts:
#Â CloudPlatform AlertManager receiver to route promethues alerts to slack
  alertSeverity: digital-prison-service-dev

